[package]
name = "axcompute"
version.workspace = true
edition.workspace = true
authors = ["AeroTensor Team"]
description = "AeroTensor AI Compute Engine, Ring Buffers (SQ/CQ) and GEMM Operators"
license.workspace = true

[dependencies]
log = "0.4"
kspin = "0.2"
axtensor_mem = { workspace = true }
axtp = { workspace = true, optional = true }

[features]
default = []
